### PR TITLE
Remove duplicate black lab

### PR DESCRIPTION
**Pull request by winny-**
Moved the image with the greatest ID to the duplicate's place.

Dupes:
- [image236.png](https://github.com/beedog/beedog.github.io/tree/14840d0dd16d4fa8f14543cd9841c9b6b2b10d6b/image236.png) 
- [image248.png](https://github.com/beedog/beedog.github.io/tree/14840d0dd16d4fa8f14543cd9841c9b6b2b10d6b/image248.png)

### CODE REVIEW

**Comment by woodruffw** [comment]
Please run these commands in the project directory:

``` bash
cd util/
bash reorder.sh
```

That'll make sure continuity is preserved. Make sure you're in the `util` directory when you run it.

**Comment by woodruffw** [comment]
Who needs small diffs? Merging #1.

**Comment by winny-** [comment]
Viewing this page is literally making my browser stutter (!)

**Comment by woodruffw** [comment]
Good.

**Pull request merged**
